server:
  port: 9090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost/UserManagementApp1
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  mail:
    host: gmail.smtp.com
    port: 587
    username: <email-id>
    password: <pwd>
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true